# mutation arrayUpload($files:FotoEntrada!){
#   arrayUpload(files:$files){
#     filename
#     path
#   }
# }
mutation arrayUpload($files:[FotoEntrada]!){
  arrayUpload(files:$files){
    filename
    path
    id
  }
}